version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:15
    container_name: cabez_postgres_container
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
      POSTGRES_DB: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Hasura GraphQL Engine
  hasura:
    image: hasura/graphql-engine:v2.33.1
    container_name: hasura_container
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://yourusername:yourpassword@postgres:5432/yourdatabase
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: youradminsecret
    ports:
      - "8080:8080"

  # FastAPI Service
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    depends_on:
      - postgres
      - hasura
    ports:
      - "8000:8000"

volumes:
  postgres_data:
